name = "archimedes"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Archimedes"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.0-rc2"

[[lean_lib]]
name = "Archimedes"
